### PR TITLE
Quick modification to make this workable with Python3 and PyQt5

### PR DESCRIPTION
**Pull request by hjmr**
Not yet checked well but seems working.

### CODE REVIEW

**Comment by turkishviking** [comment]
wow you are making an incredible work, thank you! I will review that this week end

**Comment by jc1bert** [comment]
Hi,

I just gave it a try with some bots created with my students.
Everything seems to work perfectly, I’ll be using it in december without the hassle of running a separate python 2 + pyQt4 install.

Thanks a lot!

**Comment by hjmr** [comment]
@turkishviking Thank YOU for starting this nice project! It was much easier than I expected to port this to PyQt5. I need little modifications only as you can see in the commitment.

@Bobyl Thank you for checking. I'm also thinking to use this in my programming class. I think it's nice to have another place (another repository?) to store robots instead of adding to this repository. Then you can check techniques used in others' robots more easily.

**Comment by turkishviking** [comment]
Hi all, unfortunately, I have a power failure at home, this will take longer to me to make the review. @hjmr another repo? why not, I will have to link it to this repo, see you soon

**Pull request merged**
